### ISSUE TITLE
New issue 

### ISSUE THREAD

**Issue by Xx-Mohit-xX** [BUGO07/discord-button-pagination#1]
Can you guys do something to fix the below error , i dont have access to node_modules so i cant
![Screenshot_20210805-102047_Samsung Internet](https://user-images.githubusercontent.com/75924613/128292811-611f2df8-984f-4f43-851c-69319e53056d.jpg)

**Comment by BUGO07** [comment]
> Can you guys do something to fix the below error , i dont have access to node_modules so i cant
> ![Screenshot_20210805-102047_Samsung Internet](https://user-images.githubusercontent.com/75924613/128292811-611f2df8-984f-4f43-851c-69319e53056d.jpg)

Hey, so this doesn't have anything to do with the package. its located at discord.js directory. I believe this error happened because your node.js is outdated. Please use NodeJS 14 or above. NodeJS 14 is recomended for this package, also this package is discontinued so if there's any bugs with it, i'm not responsible to fix them.

**Comment by Xx-Mohit-xX** [comment]
My bad, sorry for disturbing
